---
# File: main.yml - Handlers for Consul

- name: restart consul
  service:
    name: consul
    state: restarted

- name: start consul
  service:
    name: consul
    enabled: yes
    state: started

- name: stop consul
  service:
    name: consul
    enabled: yes
    state: stopped

- name: reload consul
  service:
    name: consul
    enabled: yes
    state: reloaded

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: start dnsmasq
  service:
    name: dnsmasq
    enabled: yes
    state: started
