---
- name: Install filebeat
  shell: wget -qO- https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{filebeat_version}}.deb 
  shell: dpkg -i filebeat-{{filebeat_version}}.deb

- name: Register filebeat service in consul
  copy: src=filebeat.yml dest=/etc/filebeat/filebeat.yml owner=root group=root mode=0644

- name: make sure filebeat is running
  service:
    name: filebeat
    state: started
    enabled: yes
