---
# File: dnsmasq.yml - Dnsmasq tasks for Consul

- name: Install Dnsmasq package
  apt:
    name: dnsmasq
    state: present
  tags: dnsmasq, installation

- name: Stop Dnsmasq service
  service:
    name: dnsmasq
    state: stopped

- name: Create Dnsmasq configuration
  template:
    src: consul.j2
    dest: /etc/dnsmasq.d/consul
    owner: root
    group: root
    mode: 0644
  notify: start dnsmasq
  tags: dnsmasq
