---
# File: install.yml - package installation tasks for Consul

- name: Install Debian packages
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - git
    - unzip
  when: ansible_os_family == "Debian"

- name: Install RedHat packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - unzip
  when: ansible_os_family == "RedHat"

- name: Read package checksum file
  local_action: stat path="{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  become: no
  run_once: true
  register: consul_checksum
  tags: installation

- name: Download package checksum file
  local_action: get_url url="{{ consul_checksum_file_url }}" dest="{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS"
  become: no
  run_once: true
  tags: installation
  when: consul_checksum.stat.exists == False

- name: Read package checksum
  local_action: shell grep "{{ consul_pkg }}" "{{ role_path }}/files/consul_{{ consul_version }}_SHA256SUMS" | awk '{print $1}'
  become: no
  run_once: true
  register: consul_sha256
  tags: installation

- name: Check Consul package file
  local_action: stat path="{{ role_path }}/files/{{ consul_pkg }}"
  become: no
  run_once: true
  register: consul_package
  tags: installation

- name: Download Consul package
  local_action: get_url url="{{ consul_zip_url }}" dest="{{ role_path }}/files/{{ consul_pkg }}" checksum="sha256:{{ consul_sha256.stdout }}" timeout="42"
  become: no
  run_once: true
  tags: installation
  when: consul_package.stat.exists == False

- name: Unarchive Consul package
  local_action: unarchive src="{{ role_path }}/files/{{ consul_pkg }}" dest="{{ role_path }}/files/" creates="{{ role_path }}/files/consul"
  become: no
  run_once: true
  tags: installation

- name: Install Consul
  copy:
    src: "{{ role_path }}/files/consul"
    dest: "{{ consul_bin_path }}/consul"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  tags: installation

- name: Download Consul SSL package
  local_action: get_url url="{{ consul_ssl_url }}" dest="{{ role_path }}/files/consulssl.zip"
  become: no
  run_once: true
  tags: installation

- name: Unarchive Consul SSL package
  local_action: unarchive src="{{ role_path }}/files/consulssl.zip" dest="{{ consul_ssl_path }}" owner="{{ consul_user }}" group="{{ consul_group }}" mode=0600  
  become: no
  run_once: true
  tags: installation

- name: Cleanup
  local_action: file path="{{ item }}" state="absent"
  become: no
  with_fileglob: "{{ role_path }}/files/*"
  run_once: true
  tags: installation
